$quote "
$set 1
2  Notation '{0}' has already been declared
3  Attribute '{0}' has already been declared for element '{1}'
4  Encoding ({0}, from XMLDecl or manually set) contradicts the auto-sensed encoding, ignoring it
5  Element '{0}' was referenced in a content model but never declared
6  Element '{0}' was referenced in an attlist but never declared
7  An exception occurred! Type:{0}, Message:{1}
10  {0} is unsupported
11  Error: Top level complexType has no name - declaration ignored
12  Globally-declared attribute must have a name - attribute declaration ignored
13  Attribute must have a name or a ref - attribute declaration ignored
14  Globally-declared element must have a name - element declaration ignored
15  Element must have a name or a ref attribute - element ignored
16  <group> must have a name or a ref attribute - declaration ignored
17  <attributeGroup> must have a name or a ref attribute - declaration ignored
18  Anonymous complexType in element {0} has a name attribute
19  Anonymous simpleType in element {0} has a name attribute
20  The content of an element information item does not match (annotation?, (simpleType | complexType)?, (unique | key | keyref)*)
21  Untyped element: {0}
22  Error in content of simpleType
23  Expected simpleType in 'list' declaration for {0}
24  List | Union | Restriction content is invalid for type {0}
25  Error in content of derivation by list for {0}
26  Expected simpleType in 'restriction' declaration for {0}
27  Facet {0} already defined - ignoring
28  Expected simpleType in 'union' declaration for {0}
29  SimpleType content is empty
30  The content of the simpleContent element is invalid. The content must be RESTRICTION or EXTENSION
31  The BASE attribute must be specified for the RESTRICTION or EXTENSION element
32  The content of the complexContent element is invalid. The content must be RESTRICTION or EXTENSION
33  Error in content of <schema> element information item
34  Content (annotation?,..) is incorrect for type {0}
35  Unknown simpleType: {0}
36  Unknown complexType: {0}
37  Prefix: '{0}' can not be resolved to a URI
38  Ref element {0} not found in the Schema
39  Type not found in {0}:{1}
40  Could not find top level attribute: {0}
41  Invalid child '{0}' in the complex type
42  Base type could not be found: {0}
43  No attribute '{0}' was defined in schema: {1}
44  Error creating datatype validator: {0}
45  Invalid child following the simpleContent child in the complexType
46  Invalid child following the complexContent child in the complexType
47  The 'block' attribute values of a complexType must be #all | list(restriction,extension); {0} was found
48  The 'final' attribute values of a complexType must be #all | list(restriction,extension); {0} was found
49  An attribute cannot have both 'fixed' and 'default' present at the same time - default used
50  If default and use are both present, use must have the value 'optional'.
51  Local attribute:{0} has also a ref defined - name ignored
52  Global attribute:'{0}' cannot have a ref defined
53  Error: Attribute '{0}' declared more than once in the same scope- ignoring
54  Attribute declarations may not contain both a type and a simpleType declaration
55  SimpleType ({0}:{1}) for attribute: {2} not found
56  An element cannot have both 'fixed' and 'default' present at the same time
57  {0}:'{1}' has also a ref defined - name ignored
58  ref cannot appear with any of type, abstract, block, final, nillable, default or fixed
59  Invalid {0} name:'{1}' - declaration ignored
60  Globally-declared element {0} cannot have a ref attribute - ref ignored
61  Element '{0}' cannot have both a type attribute and a simpleType/complexType type child
62  Element {0} has a fixed or default value and must have a mixed simple or simple content model
63  The simpleType {0} that {1} uses has a value of 'final' which does not permit extension
64  The type '{0}' specified as the base in the simpleContent element must not have complexContent
65  The type '{0}' is a simple type. It cannot be used in a derivation by RESTRICTION for a complexType
66  Invalid child following the RESTRICTION or EXTENSION element in the simpleContent definition
67  Invalid child following the RESTRICTION or EXTENSION element in the complexContent definition
68  Annotation can only appear once: type {0}
69  The base type {0} does not allow itself to be used as the base for a restriction and/or as a type in a list and/or union
70  The value 'substitution' already in the list
71  The value 'union' is already in the list
72  The value 'extension' is already in the list
73  The value 'list' is already in the list
74  The value 'restriction' is already in the list
75  Invalid block value: {0}
76  Invalid final value: {0}
77  Element {0} cannot be part of the substitution group headed by {1}
78  Element {0} has a type which does not derive from the type of the element at the head of the substitution group
79  Duplicate element decl in the same scope: {0}
80  The 'block' attribute values of an element must be #all | list(substitution,restriction,extension); {0} was found
81  The 'final' attribute values of an element must be #all | list(restriction,extension); {0} was found
82  Invalid value '{0}' for attribute: '{1}'.
83  Ref is present, and simpleType/form/type found
84  Duplicate reference attribute {0}:{1} in complexType
85  Derivation by restriction is forbidden by either the base type '{0}' or the schema
86  Derivation by extension is forbidden by either the base type '{0}' or the schema
87  The base type specified in the complexContent element must be a complexType
88  Imported schema '{0}' has a different targetNameSpace '{1}' from what's declared '{2}'
89  Could not get the doc root for imported Schema: {0}
90  A schemaLocation attribute must be specified on '{0}' element.
91  Included schema '{0}' has a different targetNameSpace '{1}'
92  At most one <annotation> element is expected in the content.
93  The content must be (annotation?, simpleType?) for attribute '{0}={1}'
94  Attribute '{0}' must appear in {1} {2} declarations
95  Attribute '{0}' cannot appear in {1} {2} declarations
96  Value of minOccurs '{0}' must not be greater than value of maxOccurs '{1}'
97  'anyAttribute' elements can contain at most one 'annotation' element in their children
98  Global <{0}> must have a name - declaration ignored
99  No circular definitions are allowed: '{0}'
100  Global {0}:'{1}' declared more than once or also declared as {2}
101  Global {0}:'{1}' declared more than once
102  Invalid value '{0}' for facet 'whiteSpace'. Value should be 'collapse'.
103  The namespace of an <import> element must be different from the targetNamespace of the <import>ing schema
104  If the namespace on an <import> element is not present, the <import>ing schema must have a targetNamespace
105  Element '{0}' must not have a value constraint:'{1}' as its type is derived from ID
106  It is an error for NOTATION to be used directly in a schema in element/attribute '{0}'
107  For element '{0}', the {content type} is mixed, then the {content type}'s particle must be emptiable
108  The content of complexType is EMPTY, but base is not empty or does not have emptiable particle.
109  The content type of the base type:'{0}' and derived type:'{1}' must both be mixed or element-only.
110  The content type is not a valid restriction of the content type of the base.
111  Derivation by extension or restriction is forbidden by either the base type '{0}' or the schema
112  The {item type definition} must have {variety} of atomic or union (where all member types must be atomic)
113  The {member type definitions} must all have {variety} of atomic or list
114  The group:'0' must contain (all | choice | sequence)
115  The attributeGroup:'0' must match (annotation?. ((attribute | attributeGroup)*, anyAttribute?))
116  The child of a model group definition must not specify either the minOccurs or maxOccurs attribute.
117  The {0} -'{1}:{2}'- not found in the schema
118  A group whose content is 'all' must only appear as the content type of a complex type definition.
119  When a model group has {compositor} 'all' which constitutes the {content type} of a complex type, minOccurs=maxOccurs=1
120  In an 'all' schema component, the value of minOccurs/maxOccurs of an element must be '0' or '1'.
121  Circular attributeGroup reference -{0}- is disallowed outside <redefine>
122  Attribute '{0}' already defined in base and should not appear in derivation by extension.
123  The intensional intersection of {attributes wildcard}s must be expressible
124  Base type definition does not have any attributes
125  Attribute '{0}' has an inconsistent REQUIRED setting with that of the base
126  Type of attribute '{0}' must be validly derived from type of attribute in base
127  Attribute '{0}' is either not fixed, or has a different value from that of the base
128  Attribute '{0}' has invalid target namespace with respect to a base wildcard constraint or, base has no wildcard
129  An attribute wildcard is present in the derived type, but not in the base
130  The attribute wildcard in the derived type is not a valid subset of that in the base
131  Attribute '{0}' cannot modify the 'use' attribute in a derived type, if base attribute use is prohibited
132  The wildcard attribute in the derived type must be identical to or stronger than the one in the base.
133  Content of <all> is restricted to elements only. '{0}' encountered and ignored.
134  Redefined schema '{0}' has a different targetNameSpace '{1}'.
135  A simpleType child of a <redefine> must have a restriction element as a child
136  The base attribute of the restriction child of a simpleType, must be the same as the redefine simpleType's name attribute
137  A complexType child of a <redefine> must have a restriction or extension element as a grandchild
138  The base attribute of a restriction/extension must be the same as the complexType's name attribute in <redefine>
139  The group '{0}' which contains a reference to a group being redefined must have minOccurs = maxOccurs = 1
140  Could not find a declaration in the schema to be redefined corresponding to '{0}'
141  If a group child of a <redefine> element contains a group ref'ing itself, it must have exactly 1 reference.
142  If an attributeGroup of a <redefine> element contains a reference to itself, such reference must be exactly 1
143  A <redefine> element cannot contain a child of type '{0}'
144  The declaration for notation '{0}' is invalid
145  The notation declaration '{0}:{1}' is not found
146  More than one identity constraint named '{0}'.
147  The content of an identity constraint must match (annotation?, selector, field+)
148  Key reference declaration '{0}' refers to unknown key with name '{1}'.
149  Cardinality of fields for keyref '{0}' and key '{1}' must match.
150  Xpath expression is either missing or empty
151  The {value constraint} of an attribute ref is not fixed or different from the fixed {value constraint} of '{0}'
152  The {type definition} for attribute '{0}={1}' is or is derived from ID, and must not have {value constraint}
153  More than one attribute derived from type ID cannot appear in the same complex type - '{0}' ignored
154  More than one attribute derived from type ID cannot appear in the same attribute group - '{0}' ignored
155  '' is not a legal value for the targetNamespace attribute; the attribute must be absent or contain a nonempty value
156  {0}
157  An exception occurred! Type:{0}, Message:{1}
158  Invalid Redefine: '{0}' has already been included or redefined
159  Schema Representation Constraint: Namespace '{0}' is referenced without <import> declaration
160  An 'all' model group that's part of a complex type definition must constitute the entire content type of the definition
161  An <annotation> can only contain <appinfo> and <documentation> elements
162  Invalid facet name: {0}
163  The root element name of an XML Schema should be 'schema'.
164  Circular substitution groups are disallowed for element '{0}'.
165  For '{0}' to be a member of the substitution group set of '{1}', its {abstract} must be false.
166  The namespace of element '{0}' must be from the schema namespace.
167  The {target namespace} of '{0}' must not match 'http://www.w3.org/2001/XMLSchema-instance'.
170  Expected comment or CDATA
171  Expected an attribute name
172  Expected a notation name
173  Repetition of individual elements is not legal for mixed content models
174  Bad default attribute declaration
175  Expected default attribute declaration, assuming #IMPLIED 
176  Attribute list syntax error
177  Expected equal sign
178  Duplication attribute name
179  Bad ID, '{0}', for xml:lang attribute
180  Expected an element name
181  Must start with an XMLDecl
182  Comments must start with <!--
183  Invalid document structure
184  Expected a 'version=', 'encoding=', or 'standalone='
185  Bad XML version string
186  Unsupported XML version, '{0}'
187  Unterminated XML decl
188  Bad XML encoding declaration, '{0}'
189  Bad standalone declaration
190  Unterminated comment
191  Processing instruction name expected
192  Unterminated processing instruction
193  Invalid character (Unicode: 0x{0})
194  Unexpected text before root element
195  Unterminated start tag, '{0}'
196  Expected an attribute value
197  Unterminated end tag
198  Expected type (CDATA, ID, NMTOKEN, ..), for attribute '{0}' of element '{1}'
199  Expected end of tag '{0}'
200  Expected tag name, comment, PI, or other markup
201  Not valid after content
202  Expected comment
203  Expected comment or processing instruction
204  Expected whitespace
205  No root element in DOCTYPE
206  Expected quoted string
207  Expected public id
208  Invalid character in public id (Unicode: 0x{0})
209  Unterminated DOCTYPE declaration
210  Invalid character in internal subset (Unicode: 0x{0})
211  Expected CDATA section
212  Invalid initial name character
213  Invalid name character
214  Unexpected whitespace
215  Invalid character in attribute value {0} (Unicode: 0x{1})
216  Expected a markup declaration
217  Text declaration not legal here
218  Conditional section in internal subset
219  Expected parameter entity name
220  Unterminated entity declaration, '{0}'
221  Invalid character reference
222  Unterminated character reference
223  Expected entity name for reference
224  Entity '{0}' was not found
225  Unparsed entity references, '{0}', not valid here
226  Unterminated entity reference
227  Recursive entity expansion
228  Partial markup in entity value
229  Unterminated element declaration, '{0}'
230  Expected content specification expression for element '{0}'
231  Expected asterisk
232  Unterminated Content model
233  Expected system id
234  Expected system or public id
235  Unterminated notation declaration
236  Expected ',', '|', or ')' characters
237  Expected '|' or ')' characters
238  Expected ',' or ')' characters or close parenthesis in content model of element '{0}'
239  Expected enumeration value for attribute '{0}'
240  Expected | enumeration separator, or closing paren
241  Unterminated entity literal
242  There are more end tags than start tags
243  Expected an open parenthesis
244  The attribute '{0}' is already used in element '{1}'
245  A '<' character cannot be used in attribute '{0}', except through &lt;
246  A leading surrogate character was not followed by a legal second character
247  Expected ']]>' to end a conditional section
248  Expected INCLUDE or IGNORE here
249  Expected [ to follow INCLUDE or IGNORE
250  Expected a TextDecl here: <?xml ....
251  Expected a XMLDecl here: <?xml ....
252  Unexpected end of entity {0}
253  A PE propagated out of the int/ext subset, discarding extra text
254  An extra ] character was found an ignored
255  PE refs are not allowed inside markup in the internal subset
256  An entity propagated out of the content section into Miscellaneous
257  Expected &# to be followed by a numeric character value
258  Expected an open bracket ('[') here
259  The sequence ']]>' is not allowed in character data
260  Illegal sequence '--' in comment
261  Unterminated CDATA section
262  Expected NDATA
263  NDATA is not legal for parameter entities
264  Hex radix character refs must use 'x', not 'X'
265  '{0}' has already been set. Ignoring redundant setting
266  The XMLDecl strings must be in the order: version, encoding, standalone
267  External entities cannot be referred to from attribute values
268  The XML or Text decl must start with '<?xml ', not '<?XML '
269  Expected a literal entity value or PUBLIC/SYSTEM id
270  '{0}' is not a valid digit for the indicated radix
271  The input ended before all started tags were ended. Last tag started was '{0}'
272  The content model for element '{0}' is ambiguous
273  Nested CDATA sections are not allowed
274  The prefix '{0}' has not been mapped to any URI
275  The start and the end tag were in the different entities
276  The main XML document cannot be empty
277  CDATA is not allowed outside the root element
278  Only numeric character entities or special character entities are legal here
279  Got an unexpected trailing surrogate character
280  No processing instruction starts with 'xml'
281  The XML or Text declaration must start at line/column 1/1
282  The 'version=' string is required in an XMLDecl
283  The 'standalone=' string is only allowed in the main XML entity
284  The 'encoding=' string is required in an Text Decl
285  When namespaces are enabled, a name can have only one colon character
286  When namespaces are enabled, the colon cannot be the first or last character
287  Colons are not allowed in this name when namespaces are enabled
288  A system exception occurred during processing
289  An exception occurred! Type:{0}, Message:{1}
290  Unexpected end of file exception. Message: {0}
291  UnexpectedError
292  The schemaLocation attribute does not contain pairs of values.
293  Internal error: don't have a GrammarResolver for TraverseSchema
294  Fatal error encountered during schema scan
295  Reference to external entity declaration '{0}' is not allowed in a standalone document.
296  Partial markup in parameter entity replacement text in a complete declaration.
297  The value of the attribute '{0}' is invalid. Prefixed namespace bindings may not be empty.
298  The prefix 'xmlns' cannot be bound to any namespace explicitly.
299  The namespace for 'xmlns' cannot be bound to any prefix explicitly.
300  The prefix 'xml' cannot be bound to any namespace other than its usual namespace.
301  The namespace for 'xml' cannot be bound to any prefix other than 'xml'.
302  Element '{0}' cannot have 'xmlns' as its prefix.
303  Complex Type Definition Representation OK - 2.2: <restriction> must have a <simpleType> child.


$set 2
2  Unknown element '{0}'
3  Attribute '{0}' not defined
4  Notation '{0}' was referenced but never declared
5  Root element different from DOCTYPE
6  Required attribute '{0}' was not provided
7  Element '{0}' is not valid for content model: '{1}'
8  ID attributes must be #IMPLIED or #REQUIRED
9  This type of attribute cannot have an empty value
10  Element '{0}' has already been declared
11  Element '{0}' has more than one ID attribute
12  ID '{0}' has already been used
13  ID attribute '{0}' was referenced but never declared
14  Attribute '{0}' refers to an unknown notation '{1}'
15  Element '{0}' was used in the DOCTYPE but never declared
16  Empty content not valid for content model: '{0}'
17  Attribute '{0}' is not declared for element '{1}'
18  Attributes of type ENTITY/ENTITIES must refer to an external, unparsed entity
19  Attribute '{0}' refers to an unknown entity '{1}'
20  Not enough elements to match content model : '{0}'
21  No character data is allowed by content model
22  Attribute '{0}' does not match its defined enumeration or notation list
23  The values for attribute '{0}' must be names or name tokens
24  Attribute '{0}' does not support multiple values
25  Attribute '{0}' has a value, '{1}', that does not match its #FIXED value, '{2}'
26  Element types cannot be duplicated in Mixed content models
27  No validator for datatype {0}
28  Incorrect datatype: {0}
29  {0} is not a datatype.
30  The content attribute must be 'textOnly' if you specify a type attribute.
31  {0} is unsupported
32  Nested Element decls only allowed in elementOnly content
33  Element references only allowed in mixed or elementOnly content
34  {0} only allowed in elementOnly content.
35  {0} not allowed if the order is all.
36  Datatype qualifiers can only be used if you specify a type attribute.
37  The datatype qualifier {0} is not supported.
38  Error: {0} content must be one of element, group, modelGroupRef. Saw {1}
39  Unknown base type {0} for type {1}.
40  Can only have one of type and ref attributes.
41  A <{0}> declaration that has a ref attribute, cannot have child content.
42  Incorrect type for {0}'s default value: {1}
43  Illegal content {0} in attribute group
44  Value of {0} is not an integer.
45  Datatype error: Type:{0}, Message:{1}.
46  Schema error: Type:{0}, Message:{1}
47  The type of the element has already been declared.
48  Prohibited Attribute is found.
49  Illegal xml:space declaration.
50  {0} is not a boolean.
51  {0} is not a decimal.
52  Facets are inconsistent with base type.
53  Illegal value {0} for facet {1}.
54  Illegal Facet for decimal type.
55  Unknown Facet: {0}.
56  Invalid value for Enum constant: {0}.
57  {0} is out of bounds:[ {1} {3} X  {4} {2} ].
58  {0} is not one of the specified enum values.
59  {0} is not an integer.
60  Illegal Facet for Integer type.
61  {0} is not a double.
62  Illegal Facet for Real type.
63  Scale Facet must be less than or equal to Precision Facet
64  {0} has exceeded the precision Facet {1}
65  {0} has exceeded the scale Facet {1}
66  {0} is not a float.
67  Can't get back Schema document's root element {0}.
68  Schema in {0} has a different target namespace from the one specified in the instance document {1}.
69  In element {0}: Can not have element children within a simple type content.
70  This element {0} has a simpletype but no datatype validator was found.
71  There is no Grammar for uri: {0}.
72  {0}
73  xsi:nil must not be specified for the element {0} with nillable equals false
74  Element {0} with attribute xsi:nil=true must be empty
75  Content of element '{0}' is different from the fixed attribute value in the element's schema declaration.
76  No datatype validator was found for this attribute {0}.
77  Schema error during parsing
78  Element '{0}' should be qualified
79  Element '{0}' should be un-qualified
80  Reference to external entity declaration '{0}' is not allowed in a standalone document.
81  Attribute '{0}' for element '{1}' has a default value and must be specified in a standalone document.
82  Attribute '{0}' must not be changed by normalization in a standalone document.
83  White space must not occur between externally declared elements with element content in a standalone document.
84  Entity '{0}' was not found
85  Partial markup in parameter entity replacement text.
86  Failed to validate '{0}'
87  '{0}' and '{1}' violate the Unique Particle Attribution rule
88  Abstract type '{0}' should not be used in xsi:type
89  A member of abstract element {0} substitution group must be specified
90  Element {0} is declared with a type that is abstract.  Use xsi:type to specify a non-abstract type
91  Unresolved type '{0}' found in xsi:type handling
92  Type '{0}' that is used in xsi:type is not derived from the type of element '{1}'
93  Element '{0}' has blocking constraint and does not permit substitution
94  Attribute '{0}' should be qualified
95  Attribute '{0}' should be un-qualified
96  Field matches more than one value within the scope of its selector; fields must match unique values
97  Internal identity constraint error; unknown field.
98  Identity-constraint 4.2.1: element '{0}' has a key with no value.
99  Not enough values specified for <unique> identity constraint for element '{0}'.
100  Not enough values specified for <key name={1}> identity constraint for element '{0}'.
101  Not enough values specified for <keyref name={1}> identity constraint for element '{0}'.
102  Identity-constraint 4.2.3: element '{0}' has a key that matches an element that has nillable set to true.
103  Duplicate unique value declared for identity constraint of element '{0}'.
104  Duplicate key value declared for identity constraint of element '{0}'.
105  The keyref '{0}' refers to a key/unique that is out of scope.
106  The key for identity constraint of element '{0}' is not found.


$set 3
2  Warning: The primary document entity could not be opened. Id={0}
3  Warning: No caching of grammar set, a grammar with same key found in the cache pool.
6  The index is beyond the array bounds 
7  The new size is less than the old one
8  The index given was beyond the max attribute index
9  The passed AttTypes value is not known
10  The passed DefAttTypes value is not known
11  The bit index was beyond the set size
12  The bit sets are not of the same size
13  The buffer manager cannot provide any more buffers
14  The passed buffer was not found in this manager's pool
15  The pointer has not been set
16  The binary operation node had a unary node type
17  The content type must be mixed or children
18  PCDATA nodes are not valid here
19  The {0} operation is invalid for the spec type
20  The unary operation node had a binary node type
21  Unknown content model type
22  Unknown content spec type
23  The parent element has no content spec node
24  The spec type is not valid for {0}
25  The creation reason enum has an unknown value
26  The element stack is empty
27  The element stack index given was beyond the stack top
28  The element stack was already empty when a pop request occurred
29  A parent operation was requested, but only one element is on the stack
30  The enumerator contains no more elements
31  Could not open file: {0}
32  Could not query the current file position
33  Could not close the file
34  Could not seek to end of file
35  Could not seek to required position in file
36  Could not duplicate the handle
37  Could not read data from file
38  Could not write data to file
39  Could not reset file to beginning
40  Could not ascertain the file size
41  Could not determine base pathname of the file
42  The base path had too few levels to weave in relative part
43  Parse may not be called while parsing
44  A DOCTYPE was seen but the installed validator does not understand DTDs
45  Could not open DTD file '{0}'
46  Could not open external entity '{0}'
47  The end of input was not expected
48  The hash modulus cannot be zero
49  Hashing the key returned an invalid bad hash value
50  The key '{0}' could not be found in the hash table
51  Could not create mutex
52  Could not close mutex
53  Could not lock mutex
54  Could not unlock mutex
55  Could not destroy mutex
56  Internal Error on NetAccessor
57  Error on NetAccessor. Cannot determine length of remote file
58  The NetAccessor could not be initialized.
59  The host/address '{0}' could not be resolved
60  Could not create the socket for URL '{0}'
61  Could not connect to the socket for URL '{0}'
62  Could not write to the socket for URL '{0}'
63  Could not read from the socket for URL '{0}'
64  The element {0} already exists
65  Hashing the key returned an invalid bad hash value
66  The passed id is not valid for this pool
67  The modulus value cannot be zero
68  The indicated reader id was never found
69  The auto encoding enum has an unknown value
70  Could not decode first line of entity: {0}
71  End of input was hit in the middle of a multibyte sequence
72  The current transcoding service does not support source offset information
73  EBCDIC files must provide an encoding= string
74  The primary document entity could not be opened. Id={0}
75  Unbalanced start/end tags found, cannot continue
76  The call to scanNext() is illegal at this time
77  The index is past the top of stack
78  The stack is empty, cannot access members
79  The target buffer cannot have a max size of zero
80  The given radix is not supported. Use 2, 8, 10, or 16
81  The target buffer is too small to accept the results
82  The start index is past the end of the string
83  The represented value overflowed the output binary result
84  Could not write to standard err
85  Could not write to standard out
86  Could not write to console
87  String pool id was not legal
88  Could not create a default transcoder
89  The maximum size to xlat is larger than the declared block size
90  Unicode char 0x{0} is not representable in encoding {1}
91  Character {0} is not valid for encoding {1}
92  The requested block size is not equal to the size set during construction
93  An invalid multi-byte source text sequence was encountered
94  {0} is not a valid value for encoding {1}
95  Leading surrogate was not followed by trailing
96  Could not create a converter for encoding: {0}
97  The URL was not correctly formed
98  The URL used an unsupported protocol
99  Unsupported URL protocol: '{0}'
100  Only localhost is supported at this time
101  No protocol prefix present
102  Expected // after protocol
103  % must be followed by two hex digits
104  Unterminated host component
105  The base part of the URL cannot be relative
106  The base part has too few levels to weave in relative part
107  The port field must be a 16 bit decimal number
108  The passed index is past the end of the vector
109  The element id was invalid
110  When reusing the Grammar, no internal subset is allowed
111  The passed recognizer encoding was not known
112  Wrong character
113  Invalid reference number
114  A character is required after \
115  '?' is not expected.  '(?:' or '(?=' or '(?!' or '(?<' or '(?#' or '(?>'?
116  '(?<=' or '(?<!' is expected
117  A comment is not terminated
118  ')' is expected
119  Unexpected end of the pattern in a modifier group
120  ':' is expected
121  Unexpected end of the pattern in a conditional group
122  A back reference or an anchor or a lookahead or a lookbehind is expected in a conditional pattern
123  There are more than three choices in a conditional group
124  A character in U+0040-U+005f must follow \c
125  A '{' is required before a category character.
126  A property name is not closed by '}'
127  Unexpected meta character
128  Unknown property
129  A POSIX character class must be closed by ':]'
130  Unexpected end of the pattern in a character class
131  Unknown name for a POSIX character class
132  '-' is invalid here
133  ']' is expected
134  '{0}' is not a valid character range; use '\{1}' instead
135  ='[' is expected
136  ')' or '-[' or '+[' or '&[' is expected
137  The range end code point '{0}' is less than the start code point '{1}'
138  Invalid Unicode hex notation
139  Overflow in a hex notation
140  '\ x{' must be closed by '}'
141  Invalid Unicode code point
142  An anchor must not be here
143  This expression is not supported in the current option setting
144  '{0}' is not a valid character escape
145  Invalid quantifier in '{0}'. A digit is expected
146  Invalid quantifier in '{0}'. Invalid quantity or a '}' is missing
147  Invalid quantifier in '{0}'. A digit or '}' is expexted
148  Invalid quantifier in '{0}'. A min quantity must be <= a max quantity
149  Invalid quantifier in '{0}'. A quantity value overflow
150  A schema was seen but the installed validator does not understand schema
151  The {0} node type is not valid for copy
152  SubstitutionGroupComparator has no grammar resolver
153  Length Value '{0}' is invalid
154  maxLength Value '{0}' is invalid
155  minLength Value '{0}' is invalid
156  Length Value '{0}' must be a nonNegativeInteger
157  maxLength Value '{0}' must be a nonNegativeInteger
158  minLength Value '{0}' must be a nonNegativeInteger
159  It is an error for both length and maxLength to be members of facets
160  It is an error for both length and minLength to be members of facets
161  Value of maxLength '{0}' must be greater than the value of minLength '{1}'
162  Only constraining facet in boolean datatype is PATTERN
163  Invalid Facet Tag '{0}'
164  Value of Length '{0}' must be equal to the base Length '{1}'
165  Value of minLength '{0}' must be greater than or equal to the base minLength '{1}'
166  Value of minLength '{0}' must be less than or equal to the base maxLength '{1}'
167  Value of maxLength '{0}' must be less than or equal to the base maxLength '{1}'
168  Value of maxLength '{0}' must be greater than or equal to the base minLength '{1}'
169  Value of Length '{0}' must be greater than or equal to the base minLength '{1}'
170  Value of Length '{0}' must be less than or equal to the base maxLength '{1}'
171  Value of minLength '{0}' must be less than or equal to the base Length '{1}'
172  Value of maxLength '{0}' must be greater than or equal to the base Length '{1}'
173  Value of enumeration = '{0}' must be from the value space of base
174  Value of whitespace '{0}' must be one of 'preserve', 'replace', 'collapse'
175  It is an error if whiteSpace = 'preserve' or 'replace' and base.whiteSpace = 'collapse'.
176  It is an error if whiteSpace = 'preserve' and base.whiteSpace = 'replace'.
177  MaxInclusive '{0}' is invalid
178  MaxExclusive '{0}' is invalid
179  MinInclusive '{0}' is invalid
180  MinExclusive '{0}' is invalid
181  TotalDigit Value '{0}' is invalid
182  FractionDigit Value '{0}' is invalid
183  TotalDigit Value '{0}' must be a PositiveInteger
184  FractionDigit Value '{0}' must be a nonNegativeInteger
185  It is an error for both maxInclusive and maxExclusive to be specified for the same datatype
186  It is an error for both minInclusive and minExclusive to be specified for the same datatype
187  maxExclusive value '{0}' must be greater than minExclusive value '{1}'
188  maxExclusive value '{0}' must be greater than minInclusive value '{1}'
189  maxInclusive value '{0}' must be greater than minExclusive value '{1}'
190  maxInclusive value '{0}' must be greater than minInclusive value '{1}'
191  TotalDigit value '{0}' must be greater than FractionDigit value '{1}'
192  maxInclusive value '{0}' must be less than base's maxExclusive value '{1}'
193  maxInclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
194  maxInclusive value '{0}' must be greater than or equal to base's minInclusive value '{1}'
195  maxInclusive value '{0}' must be greater than base's minExclusive value '{1}'
196  maxExclusive value '{0}' must be less than or equal to base's maxExclusive value '{1}'
197  maxExclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
198  maxExclusive value '{0}' must be greater than base's minInclusive value '{1}'
199  maxExclusive value '{0}' must be greater than base's minExclusive value '{1}'
200  minExclusive value '{0}' must be less than base's maxExclusive value '{1}'
201  minExclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
202  minExclusive value '{0}' must be greater than base's minInclusive value '{1}'
203  minExclusive value '{0}' must be greater than base's minExclusive value '{1}'
204  minInclusive value '{0}' must be less than base's maxExclusive value '{1}'
205  minInclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
206  minInclusive value '{0}' must be greater than or equal to base's minInclusive value '{1}'
207  minInclusive value '{0}' must be greater than base's minExclusive value '{1}'
208  maxInclusive value '{0}' must be from the base's value space
209  maxExclusive value '{0}' must be from the base's value space
210  minInclusive value '{0}' must be from the base's value space
211  minExclusive value '{0}' must be from the base's value space
212  totalDigit value '{0}' must be less than or equal to base's totalDigit value '{1}'
213  fractDigit value '{0}' must be less than or equal to base's totalDigit value '{1}'
214  fractDigit value '{0}' must be less than or equal to base's fractDigit value '{1}'
215  maxInclusive '{0}' must be equal to base's maxInclusive '{1}' , fixed
216  maxExclusive '{0}' must be equal to base's maxExclusive '{1}' , fixed
217  minInclusive '{0}' must be equal to base's minInclusive '{1}' , fixed
218  minExclusive '{0}' must be equal to base's minExclusive '{1}' , fixed
219  totalDigit '{0}' must be equal to base's totalDigit '{1}'  , fixed
220  fractDigit '{0}' must be equal to base's fractDigit '{1}' , fixed
221  maxLen '{0}' must be equal to base's maxLen '{1}' , fixed
222  minLen '{0}' must be equal to base's minLen '{1}' , fixed
223  len '{0}' must be equal to base's len '{1}' , fixed
224  whitespace '{0}' must be equal to base's whitespace '{1}' , fixed
225  internal Error: fixed
226  Null base validator in List 
227  Null member type validators in Union 
228  Null base validator in Union
229  Union's base validator's type '{0}' must be union too 
230  Value '{0}' does not match regular expression facet '{1}'
231  Value '{0}' is not encoded in Base64 
232  Value '{0}' is not encoded in HexBin 
233  Value '{0}' with length '{1}' exceeds maximum length facet of '{2}' 
234  Value '{0}' with length '{1}' is less than minimum length facet of '{2}' 
235  Value '{0}' with length '{1}' is not equal to length facet of '{2}' 
236  Value '{0}' is not in enumeration 
237  Value '{0}' with total digits '{1}' exceeds total digit facet of '{2}' 
238  Value '{0}' with fraction digits '{1}' exceeds fraction digit facet of '{2}' 
239  Value '{0}' must be less than or equal to MaxInclusive '{1}' 
240  Value '{0}' must be less than MaxExclusive '{1}' 
241  Value '{0}' must be greater than or equal to MinInclusive '{1}' 
242  Value '{0}' must be greater than MinExclusive '{1}' 
243  Value '{0}' is not whitespace replaced 
244  Value '{0}' is not a whitespace collapsed 
245  Value '{0}' is not valid NCName 
246  Value '{0}' is not valid Name 
247  ID '{0}' is not unique 
248  Value '{0}' is not valid ENTITY 
249  Value '{0}' is not valid QName 
250  NOTATION '{0}' must be a valid QName 
251  Value '{0}' does not match any member types (of the union) 
252  Value '{0}' is NOT a valid URI 
253   Empty string encountered.
254   String contains whitespaces only.
255   More than one decimal points encountered.
256   Invalid chars encountered.
257   Null pointer encountered.
258   Cannot construct URI with null/empty '{0}' 
259   '{0}', '{1}' can only be set for a generic URI! 
260   '{0}' contains invalid escape sequence '{1}'
261   '{0}' contains invalid char '{1}'
262   '{0}' can not be set to null 
263   '{0}' is NOT conformance '{1}' 
264   No scheme found in URI
265   '{0}', '{1}' may not be specified if host is not specified 
266   '{0}', '{1}' may not be specified if path is not specified 
267   '{0}', '{1}' cannot be specified in path
268   Port no '{0}' shall be in (0, 65535) 
269   Value '{0}' shall be greater than the max Negative value '{1}' 
270   Value '{0}' shall be less than the max Negative value '{1}' 
271   Value '{0}' shall be in the range of '{1}', '{2}' 
272   Type '{0}' is invalid: internal error 
273   Value '{0}' shall have exponent. 
274  A result is not set.
275  CompactRanges - Internal Error
276  Merge Ranges - Mismatched type
277  SubtractRanges - Internal Error
278  IntersectRanges - Internal Error
279  ComplementRanges - Argument must be a RangeToken
280  Invalid category name: {0}
281  Keyword '{0}' not found
282  Reference no must be more than zero
283  Unknown option: {0}
284  Unknown token type
285  Failed to get RangeToken for: {0}
286  Not supported
287  Invalid child index
288  Replace pattern cannot match zero length string
289  Invalid replace pattern
290  Enabling the NEL option can only be called once per process.
291  {0}
292  operator new fails.  Possibly running Of memory
293  Operation is not allowed
294  Selectors cannot select attributes
295  Not allowed to have '|' at the beginning of an xpath value
296  Not allowed to have '||' in an xpath value
297  Missing attribute name in xpath
298  Expected xpath token 'NAMETEST_QNAME' or 'NAMETEST_ANY' or 'NAMETEST_NAMESPACE'
299  Prefix '{0}' not bound to namespace URI in an xpath value
300  Not allowed to have double colon in the xpath expression
301  Expected step following token 'AXISNAME_CHILD::'
302  Expected step following '//' in xpath
303  Expected step following '/' in xpath
304  '/' not allowed after '//' in xpath
305  '//' only allowed after '.' at the beginning of an xpath
306  Not allowed to have '/' at the beginning of an xpath value
307  Not allowed to select the root of an xpath
308  Empty xpath expression
309  The xpath expression cannot end with '|'
310  Invalid character following '.' in xpath
311  XPath token not supported
312  Find a solution!
313  buffer not initialized yet!
314  'T' is missing! '{0}' 
315  invalid gDay! '{0}' 
316  invalid gMonth! '{0}' 
317  invalid gMonthDay! '{0}' 
318  Duration shall start with '-' or 'P'! '{0}' 
319  Duration shall always have 'P'! '{0}' 
320  '-' can only appear at first! '{0}' 
321  Duration has invalid stuff before 'T'! '{0}' 
322  Duration has no time elements after 'T'! '{0}' 
323  Duration shall have at least element ! '{0}' 
324  Duration shall have at least one digit after the . ! '{0}' 
325  Incomplete Date ! '{0}' 
326  Invalid Date ! '{0}' 
327  Incomplete Time ! '{0}' 
328  Invalid Time ! '{0}' 
329  ms shall be present once '.' is present ! '{0}' 
330  Incomplete YearMonth! '{0}' 
331  Year separator is missing or misplaced ! '{0}' 
332  Year must have 'CCYY' format ! '{0}' 
333  Invalid leading zero in year! '{0}' 
334  no month in YearMonth ! '{0}' 
335  TimeZone is expected ! '{0}' 
336  Expecting nothing after 'Z'! '{0}' 
337  Invalid TimeZone! '{0}' 
338  The year (0000) is an illegal year value! '{0}' 
339  The month must have values 1 to 12! '{0}' 
340  The day must have values 1 to 31! '{0}' 
341  Hour must have values 0-23! '{0}' 
342  Minute must have values 0-59! '{0}' 
343  Second must have values 0-60! '{0}' 
344  Minute must have values 0-59! '{0}' 
345  Particle Derivation Restriction: The derived complexType has content, while base is empty.
346  NSCompat: The namespace of '{0}' is not allowed by wildcard in base
347  The occurrence range of '{0}' is not a valid restriction of base element's range
348  NameAndTypeOK: The Element name/uri in restriction does not match that of corresponding base element
349  NameAndTypeOK: Element '{0}' is nillable in the restriction, while it's not in the base
350  NameAndTypeOK: Element '{0}' is either not fixed, or is not fixed with the same value as in the base
351  NameAndTypeOK: The disallowed substitutions, for element '{0}', are not a superset of those of the base element
352  NameAndTypeOK: Element '{0}' has a type that does not derive from that of the base
353  NameAndTypeOK: Derived element '{0}' has fewer Identity Constraints than base element '{1}'
354  NameAndTypeOK: Derived element '{0}' has an Identity Constraint that does not appear on base element '{1}'
355  RecurseAsIfGroup: Element '{0}' belongs to a group of a variety different from that of the base
356  Occurrence range of group is not a valid restriction of occurrence range of base group
357  Recurse: There is not a complete functional mapping between the particles
358  Forbidden restriction of 'any': Choice,Seq,All,Elt
359  Forbidden restriction of 'all': Choice,Seq,Elt
360  Forbidden restriction of 'choice': All,Seq,Leaf
361  Forbidden restriction of 'sequence': Elt
362  Wildcard's occurrence range not a restriction of base wildcard's range
363  Wildcard is not a subset of corresponding wildcard in base
364  Group's occurrence range not a restriction of base wildcard's range
365  RecurseUnordered: There is not a complete functional mapping between the particles
366  MapAndSum: There is not a complete functional mapping between the particles
367  Particle derivation: Invalid content spec node type
368  NodeIDMap overflows and exceeds the largest available size


$set 4
2  Just an index
3  The index or size is negative, or greater than the allowed value
4  The specified range of text does not fit into the String
5  An attempt was made to insert a node where it is not permitted
6  A node is used in a different document than the one that created it
7  An invalid or illegal XML character is specified
8  Data is specified for a node which does not support data
9  An attempt is made to modify an object where modifications are not allowed
10  An attempt is made to reference a node in a context where it does not exist
11  The implementation does not support the requested type of object or operation
12  An attempt is made to add an attribute that is already in use elsewhere
13  A parameter or an operation is not supported by the underlying object
14  An invalid or illegal string is specified
15  An attempt is made to modify the type of the underlying object
16  An attempt is made to create or change an object in a way which is incorrect with regard to namespaces
17  An attempt is made to use an object that is not, or is no longer, usable
18  A call to a method such as insertBefore or removeChild would make the Node invalid with respect to document grammar
19  Just an index
20  The boundary-points of a Range do not meet specific requirements
21  The container of a Range's boundary-point is set to a node of an invalid type or to a node with an ancestor of an invalid type
22  Nested CDATA sections
23  Unrepresentable character data
24  Unrecognized Node Type


