$quote "
$set 1
2  Notation '{0}' has already been declared
3  Attribute '{0}' has already been declared for element '{1}'
4  Encoding ({0}, from XMLDecl or manually set) contradicts the auto-sensed encoding, ignoring it
5  Element '{0}' was referenced in a content model but never declared
6  Element '{0}' was referenced in an attlist but never declared
7  An exception occurred! Type:{0}, Message:{1}
10  {0} is unsupported
11  Error: Top level complexType has no name - declaration ignored
12  Globally-declared attribute must have a name - attribute declaration ignored
13  Attribute must have a name or a ref - attribute declaration ignored
14  Globally-declared element must have a name - element declaration ignored
15  Element must have a name or a ref attribute - element ignored
16  <group> must have a name or a ref attribute - declaration ignored
17  <attributeGroup> must have a name or a ref attribute - declaration ignored
18  Anonymous complexType in element {0} has a name attribute
19  Anonymous simpleType in element {0} has a name attribute
20  The content of an element information item does not match (annotation?, (simpleType | complexType)?, (unique | key | keyref)*)
21  Untyped element: {0}
22  Error in content of simpleType
23  Expected simpleType in 'list' declaration for {0}
24  List | Union | Restriction content is invalid for type {0}
25  Error in content of derivation by list for {0}
26  Expected simpleType in 'restriction' declaration for {0}
27  Facet {0} already defined - ignoring
28  Expected simpleType in 'union' declaration for {0}
29  SimpleType content is empty
30  The content of the simpleContent element is invalid. The content must be RESTRICTION or EXTENSION
31  The BASE attribute must be specified for the RESTRICTION or EXTENSION element
32  The content of the complexContent element is invalid. The content must be RESTRICTION or EXTENSION
33  Error in content of <schema> element information item
34  Content (annotation?,..) is incorrect for type {0}
35  Unknown simpleType: {0}
36  Unknown complexType: {0}
37  Prefix: '{0}' can not be resolved to a URI
38  Ref element {0} not found in the Schema
39  Type not found in {0}:{1}
40  Could not find top level attribute: {0}
41  Invalid child '{0}' in the complex type
42  Base type could not be found: {0}
43  No attribute '{0}' was defined in schema: {1}
44  Error creating datatype validator: {0}
45  Invalid child following the simpleContent child in the complexType
46  Invalid child following the complexContent child in the complexType
47  The 'block' attribute values of a complexType must be #all | list(restriction,extension); {0} was found
48  The 'final' attribute values of a complexType must be #all | list(restriction,extension); {0} was found
49  An attribute cannot have both 'fixed' and 'default' present at the same time - default used
50  If default and use are both present, use must have the value 'optional'.
51  Local attribute:{0} has also a ref defined - name ignored
52  Global attribute:'{0}' cannot have a ref defined
53  Error: Attribute '{0}' declared more than once in the same scope- ignoring
54  Attribute declarations may not contain both a type and a simpleType declaration
55  SimpleType ({0}:{1}) for attribute: {2} not found
56  An element cannot have both 'fixed' and 'default' present at the same time
57  {0}:'{1}' has also a ref defined - name ignored
58  ref cannot appear with any of type, abstract, block, final, nillable, default or fixed
59  Invalid {0} name:'{1}' - declaration ignored
60  Globally-declared element {0} cannot have a ref attribute - ref ignored
61  Element '{0}' cannot have both a type attribute and a simpleType/complexType type child
62  Element {0} has a fixed or default value and must have a mixed simple or simple content model
63  The simpleType {0} that {1} uses has a value of 'final' which does not permit extension
64  The type '{0}' specified as the base in the simpleContent element must not have complexContent
65  The type '{0}' is a simple type. It cannot be used in a derivation by RESTRICTION for a complexType
66  Invalid child following the RESTRICTION or EXTENSION element in the simpleContent definition
67  Invalid child following the RESTRICTION or EXTENSION element in the complexContent definition
68  Annotation can only appear once: type {0}
69  The base type {0} does not allow itself to be used as the base for a restriction and/or as a type in a list and/or union
70  The value 'substitution' already in the list
71  The value 'union' is already in the list
72  The value 'extension' is already in the list
73  The value 'list' is already in the list
74  The value 'restriction' is already in the list
75  Invalid block value: {0}
76  Invalid final value: {0}
77  Element {0} cannot be part of the substitution group headed by {1}
78  Element {0} has a type which does not derive from the type of the element at the head of the substitution group
79  Duplicate element decl in the same scope: {0}
80  The 'block' attribute values of an element must be #all | list(substitution,restriction,extension); {0} was found
81  The 'final' attribute values of an element must be #all | list(restriction,extension); {0} was found
82  Invalid value '{0}' for attribute: '{1}'.
83  Ref is present, and simpleType/form/type found
84  Duplicate reference attribute {0}:{1} in complexType
85  Derivation by restriction is forbidden by either the base type '{0}' or the schema
86  Derivation by extension is forbidden by either the base type '{0}' or the schema
87  The base type specified in the complexContent element must be a complexType
88  Imported schema '{0}' has a different targetNameSpace '{1}' from what's declared '{2}'
89  Could not get the doc root for imported Schema: {0}
90  A schemaLocation attribute must be specified on '{0}' element.
91  Included schema '{0}' has a different targetNameSpace '{1}'
92  At most one <annotation> element is expected in the content.
93  The content must be (annotation?, simpleType?) for attribute '{0}={1}'
94  Attribute '{0}' must appear in {1} {2} declarations
95  Attribute '{0}' cannot appear in {1} {2} declarations
96  Value of minOccurs '{0}' must not be greater than value of maxOccurs '{1}'
97  'anyAttribute' elements can contain at most one 'annotation' element in their children
98  Global <{0}> must have a name - declaration ignored
99  No circular definitions are allowed: '{0}'
100  Global {0}:'{1}' declared more than once or also declared as {2}
101  Global {0}:'{1}' declared more than once
102  Invalid value '{0}' for facet 'whiteSpace'. Value should be 'collapse'.
103  The namespace of an <import> element must be different from the targetNamespace of the <import>ing schema
104  If the namespace on an <import> element is not present, the <import>ing schema must have a targetNamespace
105  Element '{0}' must not have a value constraint:'{1}' as its type is derived from ID
106  It is an error for NOTATION to be used directly in a schema in element/attribute '{0}'
107  For element '{0}', the {content type} is mixed, then the {content type}'s particle must be emptiable
108  The content of complexType is EMPTY, but base is not empty or does not have emptiable particle.
109  The content type of the base type:'{0}' and derived type:'{1}' must both be mixed or element-only.
110  The content type is not a valid restriction of the content type of the base.
111  Derivation by extension or restriction is forbidden by either the base type '{0}' or the schema
112  The {item type definition} must have {variety} of atomic or union (where all member types must be atomic)
113  The {member type definitions} must all have {variety} of atomic or list
114  The group:'0' must contain (all | choice | sequence)
115  The attributeGroup:'0' must match (annotation?. ((attribute | attributeGroup)*, anyAttribute?))
116  The child of a model group definition must not specify either the minOccurs or maxOccurs attribute.
117  The {0} -'{1}:{2}'- not found in the schema
118  A group whose content is 'all' must only appear as the content type of a complex type definition.
119  When a model group has {compositor} 'all' which constitutes the {content type} of a complex type, minOccurs=maxOccurs=1
120  In an 'all' schema component, the value of minOccurs/maxOccurs of an element must be '0' or '1'.
121  Circular attributeGroup reference -{0}- is disallowed outside <redefine>
122  Attribute '{0}' already defined in base and should not appear in derivation by extension.
123  The intensional intersection of {attributes wildcard}s must be expressible
124  Base type definition does not have any attributes
125  Attribute '{0}' has an inconsistent REQUIRED setting with that of the base
126  Type of attribute '{0}' must be validly derived from type of attribute in base
127  Attribute '{0}' is either not fixed, or has a different value from that of the base
128  Attribute '{0}' has invalid target namespace with respect to a base wildcard constraint or, base has no wildcard
129  An attribute wildcard is present in the derived type, but not in the base
130  The attribute wildcard in the derived type is not a valid subset of that in the base
131  Attribute '{0}' cannot modify the 'use' attribute in a derived type, if base attribute use is prohibited
132  Content of <all> is restricted to elements only. '{0}' encountered and ignored.
133  Redefined schema '{0}' has a different targetNameSpace '{1}'.
134  A simpleType child of a <redefine> must have a restriction element as a child
135  The base attribute of the restriction child of a simpleType, must be the same as the redefine simpleType's name attribute
136  A complexType child of a <redefine> must have a restriction or extension element as a grandchild
137  The base attribute of a restriction/extension must be the same as the complexType's name attribute in <redefine>
138  The group '{0}' which contains a reference to a group being redefined must have minOccurs = maxOccurs = 1
139  Could not find a declaration in the schema to be redefined corresponding to '{0}'
140  If a group child of a <redefine> element contains a group ref'ing itself, it must have exactly 1 reference.
141  If an attributeGroup of a <redefine> element contains a reference to itself, such reference must be exactly 1
142  The declaration for notation '{0}' is invalid
143  The notation declaration '{0}:{1}' is not found
144  More than one identity constraint named '{0}'.
145  The content of an identity constraint must match (annotation?, selector, field+)
146  Key reference declaration '{0}' refers to unknown key with name '{1}'.
147  Cardinality of fields for keyref '{0}' and key '{1}' must match.
148  Xpath expression is either missing or empty
149  The complexType has content, while base is empty
150  The {value constraint} of an attribute ref is not fixed or different from the fixed {value constraint} of '{0}'
151  The {type definition} for attribute '{0}={1}' is or is derived from ID, and must not have {value constraint}
152  More than one attribute derived from type ID cannot appear in the same complex type - '{0}' ignored
153  More than one attribute derived from type ID cannot appear in the same attribute group - '{0}' ignored
154  '' is not a legal value for the targetNamespace attribute; the attribute must be absent or contain a nonempty value
155  {0}
156  An exception occurred! Type:{0}, Message:{1}
157  Invalid Redefine: '{0}' has already been included or redefined
158  Schema Representation Constraint: Namespace '{0}' is referenced without <import> declaration
159  An 'all' model group that's part of a complex type definition must constitute the entire content type of the definition
160  An <annotation> can only contain <appinfo> and <documentation> elements
161  Invalid facet name: {0}
162  The root element name of an XML Schema should be 'schema'.
165  Expected comment or CDATA
166  Expected an attribute name
167  Expected a notation name
168  Repetition of individual elements is not legal for mixed content models
169  Bad default attribute declaration
170  Expected default attribute declaration, assuming #IMPLIED 
171  Attribute list syntax error
172  Expected equal sign
173  Duplication attribute name
174  Bad ID, '{0}', for xml:lang attribute
175  Expected an element name
176  Must start with an XMLDecl
177  Comments must start with <!--
178  Invalid document structure
179  Expected a 'version=', 'encoding=', or 'standalone='
180  Bad XML version string
181  Unsupported XML version, '{0}'
182  Unterminated XML decl
183  Bad XML encoding declaration, '{0}'
184  Bad standalone declaration
185  Unterminated comment
186  Processing instruction name expected
187  Unterminated processing instruction
188  Invalid character (Unicode: 0x{0})
189  Unexpected text before root element
190  Unterminated start tag, '{0}'
191  Expected an attribute value
192  Unterminated end tag
193  Expected type (CDATA, ID, NMTOKEN, ..), for attribute '{0}' of element '{1}'
194  Expected end of tag '{0}'
195  Expected tag name, comment, PI, or other markup
196  Not valid after content
197  Expected comment
198  Expected comment or processing instruction
199  Expected whitespace
200  No root element in DOCTYPE
201  Expected quoted string
202  Expected public id
203  Invalid character in public id (Unicode: 0x{0})
204  Unterminated DOCTYPE declaration
205  Invalid character in internal subset (Unicode: 0x{0})
206  Expected CDATA section
207  Invalid initial name character
208  Invalid name character
209  Unexpected whitespace
210  Invalid character in attribute value {0} (Unicode: 0x{1})
211  Expected a markup declaration
212  Text declaration not legal here
213  Conditional section in internal subset
214  Expected parameter entity name
215  Unterminated entity declaration, '{0}'
216  Invalid character reference
217  Unterminated character reference
218  Expected entity name for reference
219  Entity '{0}' was not found
220  Unparsed entity references, '{0}', not valid here
221  Unterminated entity reference
222  Recursive entity expansion
223  Partial markup in entity value
224  Unterminated element declaration, '{0}'
225  Expected content specification expression for element '{0}'
226  Expected asterisk
227  Unterminated Content model
228  Expected system id
229  Expected system or public id
230  Unterminated notation declaration
231  Expected ',', '|', or ')' characters
232  Expected '|' or ')' characters
233  Expected ',' or ')' characters or close parenthesis in content model of element '{0}'
234  Expected enumeration value for attribute '{0}'
235  Expected | enumeration separator, or closing paren
236  Unterminated entity literal
237  There are more end tags than start tags
238  Expected an open parenthesis
239  The attribute '{0}' is already used in element '{1}'
240  A '<' character cannot be used in attribute '{0}', except through &lt;
241  A leading surrogate character was not followed by a legal second character
242  Expected ']]>' to end a conditional section
243  Expected INCLUDE or IGNORE here
244  Expected [ to follow INCLUDE or IGNORE
245  Expected a TextDecl here: <?xml ....
246  Expected a XMLDecl here: <?xml ....
247  Unexpected end of entity {0}
248  A PE propagated out of the int/ext subset, discarding extra text
249  An extra ] character was found an ignored
250  PE refs are not allowed inside markup in the internal subset
251  An entity propagated out of the content section into Miscellaneous
252  Expected &# to be followed by a numeric character value
253  Expected an open bracket ('[') here
254  The sequence ']]>' is not allowed in character data
255  Illegal sequence '--' in comment
256  Unterminated CDATA section
257  Expected NDATA
258  NDATA is not legal for parameter entities
259  Hex radix character refs must use 'x', not 'X'
260  '{0}' has already been set. Ignoring redundant setting
261  The XMLDecl strings must be in the order: version, encoding, standalone
262  External entities cannot be referred to from attribute values
263  The XML or Text decl must start with '<?xml ', not '<?XML '
264  Expected a literal entity value or PUBLIC/SYSTEM id
265  '{0}' is not a valid digit for the indicated radix
266  The input ended before all started tags were ended. Last tag started was '{0}'
267  The content model for element '{0}' is ambiguous
268  Nested CDATA sections are not allowed
269  The prefix '{0}' has not been mapped to any URI
270  The start and the end tag were in the different entities
271  The main XML document cannot be empty
272  CDATA is not allowed outside the root element
273  Only numeric character entities or special character entities are legal here
274  Got an unexpected trailing surrogate character
275  No processing instruction starts with 'xml'
276  The XML or Text declaration must start at line/column 1/1
277  The 'version=' string is required in an XMLDecl
278  The 'standalone=' string is only allowed in the main XML entity
279  The 'encoding=' string is required in an Text Decl
280  When namespaces are enabled, a name can have only one colon character
281  When namespaces are enabled, the colon cannot be the first or last character
282  Colons are not allowed in this name when namespaces are enabled
283  A system exception occurred during processing
284  An exception occurred! Type:{0}, Message:{1}
285  Unexpected end of file exception. Message: {0}
286  UnexpectedError
287  The schemaLocation attribute does not contain pairs of values.
288  Internal error: don't have a GrammarResolver for TraverseSchema
289  Fatal error encountered during schema scan
290  Reference to external entity declaration '{0}' is not allowed in a standalone document.
291  Partial markup in parameter entity replacement text in a complete declaration.


$set 2
2  Unknown element '{0}'
3  Attribute '{0}' not defined
4  Notation '{0}' was referenced but never declared
5  Root element different from DOCTYPE
6  Required attribute '{0}' was not provided
7  Element '{0}' is not valid for content model: '{1}'
8  ID attributes must be #IMPLIED or #REQUIRED
9  This type of attribute cannot have an empty value
10  Element '{0}' has already been declared
11  Element '{0}' has more than one ID attribute
12  ID '{0}' has already been used
13  ID attribute '{0}' was referenced but never declared
14  Attribute '{0}' refers to an unknown notation '{1}'
15  Element '{0}' was used in the DOCTYPE but never declared
16  Empty content not valid for content model: '{0}'
17  Attribute '{0}' is not declared for element '{1}'
18  Attributes of type ENTITY/ENTITIES must refer to an external, unparsed entity
19  Attribute '{0}' refers to an unknown entity '{1}'
20  Not enough elements to match content model : '{0}'
21  No character data is allowed by content model
22  Attribute '{0}' does not match its defined enumeration or notation list
23  The values for attribute '{0}' must be names or name tokens
24  Attribute '{0}' does not support multiple values
25  Attribute '{0}' has a value, '{1}', that does not match its #FIXED value, '{2}'
26  Element types cannot be duplicated in Mixed content models
27  No validator for datatype {0}
28  Incorrect datatype: {0}
29  {0} is not a datatype.
30  The content attribute must be 'textOnly' if you specify a type attribute.
31  {0} is unsupported
32  Nested Element decls only allowed in elementOnly content
33  Element references only allowed in mixed or elementOnly content
34  {0} only allowed in elementOnly content.
35  {0} not allowed if the order is all.
36  Datatype qualifiers can only be used if you specify a type attribute.
37  The datatype qualifier {0} is not supported.
38  Error: {0} content must be one of element, group, modelGroupRef. Saw {1}
39  Unknown base type {0} for type {1}.
40  Can only have one of type and ref attributes.
41  A <{0}> declaration that has a ref attribute, cannot have child content.
42  Incorrect type for {0}'s default value: {1}
43  Illegal content {0} in attribute group
44  Value of {0} is not an integer.
45  Datatype error: Type:{0}, Message:{1}.
46  Schema error: Type:{0}, Message:{1}
47  The type of the element has already been declared.
48  Prohibited Attribute is found.
49  Illegal xml:space declaration.
50  {0} is not a boolean.
51  {0} is not a decimal.
52  Facets are inconsistent with base type.
53  Illegal value {0} for facet {1}.
54  Illegal Facet for decimal type.
55  Unknown Facet: {0}.
56  Invalid value for Enum constant: {0}.
57  {0} is out of bounds:[ {1} {3} X  {4} {2} ].
58  {0} is not one of the specified enum values.
59  {0} is not an integer.
60  Illegal Facet for Integer type.
61  {0} is not a double.
62  Illegal Facet for Real type.
63  Scale Facet must be less than or equal to Precision Facet
64  {0} has exceeded the precision Facet {1}
65  {0} has exceeded the scale Facet {1}
66  {0} is not a float.
67  Can't get back Schema document's root element {0}.
68  Schema in {0} has a different target namespace from the one specified in the instance document {1}.
69  In element {0}: Can not have element children within a simple type content.
70  This element {0} has a simpletype but no datatype validator was found.
71  There is no Grammar for uri: {0}.
72  {0}
73  xsi:nil must not be specified for the element {0} with nillable equals false
74  Element {0} with attribute xsi:nil=true must be empty
75  Content of element '{0}' is different from the fixed attribute value in the element's schema declaration.
76  No datatype validator was found for this attribute {0}.
77  Schema error during parsing
78  Element '{0}' should be qualified
79  Element '{0}' should be un-qualified
80  Reference to external entity declaration '{0}' is not allowed in a standalone document.
81  Attribute '{0}' for element '{1}' has a default value and must be specified in a standalone document.
82  Attribute '{0}' must not be changed by normalization in a standalone document.
83  White space must not occur between externally declared elements with element content in a standalone document.
84  Entity '{0}' was not found
85  Partial markup in parameter entity replacement text.
86  Failed to validate '{0}'
87  '{0}' and '{1}' violate the Unique Particle Attribution rule
88  Abstract type '{0}' should not be used in xsi:type
89  A member of abstract element {0} substitution group must be specified
90  Element {0} is declared with a type that is abstract.  Use xsi:type to specify a non-abstract type
91  Unresolved type '{0}' found in xsi:type handling
92  Type '{0}' that is used in xsi:type is not derived from the type of element '{1}'
93  Element '{0}' has blocking constraint and does not permit substitution
94  Attribute '{0}' should be qualified
95  Attribute '{0}' should be un-qualified
96  Field matches more than one value within the scope of its selector; fields must match unique values
97  Internal identity constraint error; unknown field.
98  Identity-constraint 4.2.1: element '{0}' has a key with no value.
99  Not enough values specified for <unique> identity constraint for element '{0}'.
100  Not enough values specified for <key name={1}> identity constraint for element '{0}'.
101  Not enough values specified for <keyref name={1}> identity constraint for element '{0}'.
102  Identity-constraint 4.2.3: element '{0}' has a key that matches an element that has nillable set to true.
103  Duplicate unique value declared for identity constraint of element '{0}'.
104  Duplicate key value declared for identity constraint of element '{0}'.
105  The keyref '{0}' refers to a key/unique that is out of scope.
106  The key for identity constraint of element '{0}' is not found.


$set 3
2  Warning: The primary document entity could not be opened. Id={0}
3  Warning: No caching of grammar set, a grammar with same key found in the cache pool.
6  The index is beyond the array bounds 
7  The new size is less than the old one
8  The index given was beyond the max attribute index
9  The passed AttTypes value is not known
10  The passed DefAttTypes value is not known
11  The bit index was beyond the set size
12  The bit sets are not of the same size
13  The buffer manager cannot provide any more buffers
14  The passed buffer was not found in this manager's pool
15  The pointer has not been set
16  The binary operation node had a unary node type
17  The content type must be mixed or children
18  PCDATA nodes are not valid here
19  The {0} operation is invalid for the spec type
20  The unary operation node had a binary node type
21  Unknown content model type
22  Unknown content spec type
23  The parent element has no content spec node
24  The spec type is not valid for {0}
25  The creation reason enum has an unknown value
26  The element stack is empty
27  The element stack index given was beyond the stack top
28  The element stack was already empty when a pop request occurred
29  A parent operation was requested, but only one element is on the stack
30  The enumerator contains no more elements
31  Could not open file: {0}
32  Could not query the current file position
33  Could not close the file
34  Could not seek to end of file
35  Could not seek to required position in file
36  Could not duplicate the handle
37  Could not read data from file
38  Could not write data to file
39  Could not reset file to beginning
40  Could not ascertain the file size
41  Could not determine base pathname of the file
42  The base path had too few levels to weave in relative part
43  Parse may not be called while parsing
44  A DOCTYPE was seen but the installed validator does not understand DTDs
45  Could not open DTD file '{0}'
46  Could not open external entity '{0}'
47  The end of input was not expected
48  The hash modulus cannot be zero
49  Hashing the key returned an invalid bad hash value
50  The key '{0}' could not be found in the hash table
51  Could not create mutex
52  Could not close mutex
53  Could not lock mutex
54  Could not unlock mutex
55  Could not destroy mutex
56  Error on {0} NetAccessor. Msg: {1}
57  The NetAccessor could not be initialized. Error={0}
58  The host/address '{0}' could not be resolved
59  Could not create the socket for URL '{0}'. Error={1}
60  Could not connect to the socket for URL '{0}'. Error={1}
61  Could not write to the socket. Error={0}
62  Could not read from the socket. Error={0}
63  The element {0} already exists
64  Hashing the key returned an invalid bad hash value
65  The passed id is not valid for this pool
66  The modulus value cannot be zero
67  The indicated reader id was never found
68  The auto encoding enum has an unknown value
69  Could not decode first line of entity: {0}
70  End of input was hit in the middle of a multibyte sequence
71  The current transcoding service does not support source offset information
72  EBCDIC files must provide an encoding= string
73  The primary document entity could not be opened. Id={0}
74  Unbalanced start/end tags found, cannot continue
75  The call to scanNext() is illegal at this time
76  The index is past the top of stack
77  The stack is empty, cannot access members
78  The target buffer cannot have a max size of zero
79  The given radix is not supported. Use 2, 8, 10, or 16
80  The target buffer is too small to accept the results
81  The start index is past the end of the string
82  The represented value overflowed the output binary result
83  Could not write to standard err
84  Could not write to standard out
85  Could not write to console
86  String pool id was not legal
87  Could not create a default transcoder
88  The maximum size to xlat is larger than the declared block size
89  Unicode char 0x{0} is not representable in encoding {1}
90  Character {0} is not valid for encoding {1}
91  The requested block size is not equal to the size set during construction
92  An invalid multi-byte source text sequence was encountered
93  {0} is not a valid value for encoding {1}
94  Leading surrogate was not followed by trailing
95  Could not create a converter for encoding: {0}
96  The URL was not correctly formed
97  The URL used an unsupported protocol
98  Unsupported URL protocol: '{0}'
99  Only localhost is supported at this time
100  No protocol prefix present
101  Expected // after protocol
102  % must be followed by two hex digits
103  Unterminated host component
104  The base part of the URL cannot be relative
105  The base part has too few levels to weave in relative part
106  The port field must be a 16 bit decimal number
107  The passed index is past the end of the vector
108  The element id was invalid
109  When reusing the Grammar, no internal subset is allowed
110  The passed recognizer encoding was not known
111  Wrong character
112  Invalid reference number
113  A character is required after \
114  '?' is not expected.  '(?:' or '(?=' or '(?!' or '(?<' or '(?#' or '(?>'?
115  '(?<=' or '(?<!' is expected
116  A comment is not terminated
117  ')' is expected
118  Unexpected end of the pattern in a modifier group
119  ':' is expected
120  Unexpected end of the pattern in a conditional group
121  A back reference or an anchor or a lookahead or a lookbehind is expected in a conditional pattern
122  There are more than three choices in a conditional group
123  A character in U+0040-U+005f must follow \c
124  A Category character or '{' is required
125  A property name is not closed by '}'
126  Unexpected meta character
127  Unknown property
128  A POSIX character class must be closed by ':]'
129  Unexpected end of the pattern in a character class
130  Unknown name for a POSIX character class
131  '-' is invalid here
132  ']' is expected
133  '[' is invalid in a character class.  Write '\['
134  ']' is invalid in a character class.  Write '\]'
135  ='[' is expected
136  ')' or '-[' or '+[' or '&[' is expected
137  The range end code point '{0}' is less than the start code point '{1}'
138  Invalid Unicode hex notation
139  Overflow in a hex notation
140  '\x{' must be closed by '}'
141  Invalid Unicode code point
142  An anchor must not be here
143  This expression is not supported in the current option setting
144  Regular expression: unrecognized character '{0}' in charRange
145  A schema was seen but the installed validator does not understand schema
146  The {0} node type is not valid for copy
147  SubstitutionGroupComparator has no grammar resolver
148  Length Value '{0}' is invalid
149  maxLength Value '{0}' is invalid
150  minLength Value '{0}' is invalid
151  Length Value '{0}' must be a nonNegativeInteger
152  maxLength Value '{0}' must be a nonNegativeInteger
153  minLength Value '{0}' must be a nonNegativeInteger
154  It is an error for both length and maxLength to be members of facets
155  It is an error for both length and minLength to be members of facets
156  Value of maxLength '{0}' must be greater than the value of minLength '{1}'
157  Only constraining facet in boolean datatype is PATTERN
158  Invalid Facet Tag '{0}'
159  Value of Length '{0}' must be equal to the base Length '{1}'
160  Value of minLength '{0}' must be greater than or equal to the base minLength '{1}'
161  Value of minLength '{0}' must be less than or equal to the base maxLength '{1}'
162  Value of maxLength '{0}' must be less than or equal to the base maxLength '{1}'
163  Value of maxLength '{0}' must be greater than or equal to the base minLength '{1}'
164  Value of enumeration = '{0}' must be from the value space of base
165  Value of whitespace '{0}' must be one of 'preserve', 'replace', 'collapse'
166  It is an error if whiteSpace = 'preserve' or 'replace' and base.whiteSpace = 'collapse'.
167  It is an error if whiteSpace = 'preserve' and base.whiteSpace = 'replace'.
168  MaxInclusive '{0}' is invalid
169  MaxExclusive '{0}' is invalid
170  MinInclusive '{0}' is invalid
171  MinExclusive '{0}' is invalid
172  TotalDigit Value '{0}' is invalid
173  FractionDigit Value '{0}' is invalid
174  TotalDigit Value '{0}' must be a nonNegativeInteger
175  FractionDigit Value '{0}' must be a nonNegativeInteger
176  It is an error for both maxInclusive and maxExclusive to be specified for the same datatype
177  It is an error for both minInclusive and minExclusive to be specified for the same datatype
178  maxExclusive value '{0}' must be greater than minExclusive value '{1}'
179  maxExclusive value '{0}' must be greater than minInclusive value '{1}'
180  maxInclusive value '{0}' must be greater than minExclusive value '{1}'
181  maxInclusive value '{0}' must be greater than minInclusive value '{1}'
182  TotalDigit value '{0}' must be greater than FractionDigit value '{1}'
183  maxInclusive value '{0}' must be less than base's maxExclusive value '{1}'
184  maxInclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
185  maxInclusive value '{0}' must be greater than or equal to base's minInclusive value '{1}'
186  maxInclusive value '{0}' must be greater than base's minExclusive value '{1}'
187  maxExclusive value '{0}' must be less than or equal to base's maxExclusive value '{1}'
188  maxExclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
189  maxExclusive value '{0}' must be greater than base's minInclusive value '{1}'
190  maxExclusive value '{0}' must be greater than base's minExclusive value '{1}'
191  minExclusive value '{0}' must be less than base's maxExclusive value '{1}'
192  minExclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
193  minExclusive value '{0}' must be greater than base's minInclusive value '{1}'
194  minExclusive value '{0}' must be greater than base's minExclusive value '{1}'
195  minInclusive value '{0}' must be less than base's maxExclusive value '{1}'
196  minInclusive value '{0}' must be less than or equal to base's maxInclusive value '{1}'
197  minInclusive value '{0}' must be greater than or equal to base's minInclusive value '{1}'
198  minInclusive value '{0}' must be greater than base's minExclusive value '{1}'
199  maxInclusive value '{0}' must be from the base's value space
200  maxExclusive value '{0}' must be from the base's value space
201  minInclusive value '{0}' must be from the base's value space
202  minExclusive value '{0}' must be from the base's value space
203  totalDigit value '{0}' must be less than or equal to base's totalDigit value '{1}'
204  fractDigit value '{0}' must be less than or equal to base's totalDigit value '{1}'
205  fractDigit value '{0}' must be less than or equal to base's fractDigit value '{1}'
206  maxInclusive '{0}' must be equal to base's maxInclusive '{1}' , fixed
207  maxExclusive '{0}' must be equal to base's maxExclusive '{1}' , fixed
208  minInclusive '{0}' must be equal to base's minInclusive '{1}' , fixed
209  minExclusive '{0}' must be equal to base's minExclusive '{1}' , fixed
210  totalDigit '{0}' must be equal to base's totalDigit '{1}'  , fixed
211  fractDigit '{0}' must be equal to base's fractDigit '{1}' , fixed
212  maxLen '{0}' must be equal to base's maxLen '{1}' , fixed
213  minLen '{0}' must be equal to base's minLen '{1}' , fixed
214  len '{0}' must be equal to base's len '{1}' , fixed
215  whitespace '{0}' must be equal to base's whitespace '{1}' , fixed
216  internal Error: fixed
217  Null base validator in List 
218  Null member type validators in Union 
219  Null base validator in Union
220  Union's base validator's type '{0}' must be union too 
221  Value '{0}' does not match regular expression facet '{1}'
222  Value '{0}' is not encoded in Base64 
223  Value '{0}' is not encoded in HexBin 
224  Value '{0}' with length '{1}' exceeds maximum length facet of '{2}' 
225  Value '{0}' with length '{1}' is less than minimum length facet of '{2}' 
226  Value '{0}' with length '{1}' is not equal to length facet of '{2}' 
227  Value '{0}' is not in enumeration 
228  Value '{0}' with total digits '{1}' exceeds total digit facet of '{2}' 
229  Value '{0}' with fraction digits '{1}' exceeds fraction digit facet of '{2}' 
230  Value '{0}' must be less than or equal to MaxInclusive '{1}' 
231  Value '{0}' must be less than MaxExclusive '{1}' 
232  Value '{0}' must be greater than or equal to MinInclusive '{1}' 
233  Value '{0}' must be greater than MinExclusive '{1}' 
234  Value '{0}' is not whitespace replaced 
235  Value '{0}' is not a whitespace collapsed 
236  Value '{0}' is not valid NCName 
237  Value '{0}' is not valid Name 
238  ID '{0}' is not unique 
239  Value '{0}' is not valid ENTITY 
240  Value '{0}' is not valid QName 
241  NOTATION '{0}' must be a valid QName 
242  Value '{0}' does not match any member types (of the union) 
243  Value '{0}' is NOT a valid URI 
244   Empty string encountered.
245   String contains whitespaces only.
246   More than one decimal points encountered.
247   Invalid chars encountered.
248   Null pointer encountered.
249   Cannot construct URI with null/empty '{0}' 
250   '{0}', '{1}' can only be set for a generic URI! 
251   '{0}' contains invalid escape sequence '{1}'
252   '{0}' contains invalid char '{1}'
253   '{0}' can not be set to null 
254   '{0}' is NOT conformance '{1}' 
255   No scheme found in URI
256   '{0}', '{1}' may not be specified if host is not specified 
257   '{0}', '{1}' may not be specified if path is not specified 
258   '{0}', '{1}' cannot be specified in path
259   Port no '{0}' shall be in (0, 65535) 
260   Value '{0}' shall be greater than the max Negative value '{1}' 
261   Value '{0}' shall be less than the max Negative value '{1}' 
262   Value '{0}' shall be in the range of '{1}', '{2}' 
263   Type '{0}' is invalid: internal error 
264   Value '{0}' shall have exponent. 
265  A result is not set.
266  CompactRanges - Internal Error
267  Merge Ranges - Mismatched type
268  SubtractRanges - Internal Error
269  IntersectRanges - Internal Error
270  ComplementRanges - Argument must be a RangeToken
271  Invalid category name: {0}
272  Keyword '{0}' not found
273  Reference no must be more than zero
274  Unknown option: {0}
275  Unknown token type
276  Failed to get RangeToken for: {0}
277  Not supported
278  Invalid child index
279  Invalid quantifier in '{0}'
280  Enabling the NEL option can only be called once per process.
281  {0}
282  operator new fails.  Possibly running Of memory
283  Operation is not allowed
284  Selectors cannot select attributes
285  Not allowed to have '|' at the beginning of an xpath value
286  Not allowed to have '||' in an xpath value
287  Missing attribute name in xpath
288  Expected xpath token 'NAMETEST_QNAME' or 'NAMETEST_ANY' or 'NAMETEST_NAMESPACE'
289  Prefix '{0}' not bound to namespace URI in an xpath value
290  Not allowed to have double colon in the xpath expression
291  Expected step following token 'AXISNAME_CHILD::'
292  Expected step following '//' in xpath
293  Expected step following '/' in xpath
294  '/' not allowed after '//' in xpath
295  '//' only allowed after '.' at the beginning of an xpath
296  Not allowed to have '/' at the beginning of an xpath value
297  Not allowed to select the root of an xpath
298  Empty xpath expression
299  The xpath expression cannot end with '|'
300  Invalid character following '.' in xpath
301  XPath token not supported
302  Find a solution!
303  buffer not initialized yet!
304  'T' is missing! '{0}' 
305  invalid gDay! '{0}' 
306  invalid gMonth! '{0}' 
307  invalid gMonthDay! '{0}' 
308  Duration shall start with '-' or 'P'! '{0}' 
309  Duration shall always have 'P'! '{0}' 
310  '-' can only appear at first! '{0}' 
311  Duration has invalid stuff before 'T'! '{0}' 
312  Duration has no time elements after 'T'! '{0}' 
313  Duration shall have at least element ! '{0}' 
314  Incomplete Date ! '{0}' 
315  Invalid Date ! '{0}' 
316  Incomplete Time ! '{0}' 
317  Invalid Time ! '{0}' 
318  ms shall be present once '.' is present ! '{0}' 
319  Incomplete YearMonth! '{0}' 
320  Year separator is missing or misplaced ! '{0}' 
321  Year must have 'CCYY' format ! '{0}' 
322  Invalid leading zero in year! '{0}' 
323  no month in YearMonth ! '{0}' 
324  TimeZone is expected ! '{0}' 
325  Expecting nothing after 'Z'! '{0}' 
326  Invalid TimeZone! '{0}' 
327  The year (0000) is an illegal year value! '{0}' 
328  The month must have values 1 to 12! '{0}' 
329  The day must have values 1 to 31! '{0}' 
330  Hour must have values 0-23! '{0}' 
331  Minute must have values 0-59! '{0}' 
332  Second must have values 0-60! '{0}' 
333  Minute must have values 0-59! '{0}' 
334  NSCompat: The namespace of '{0}' is not allowed by wildcard in base
335  The occurrence range of '{0}' is not a valid restriction of base element's range
336  NameAndTypeOK: The Element name/uri in restriction does not match that of corresponding base element
337  NameAndTypeOK: Element '{0}' is nillable in the restriction, while it's not in the base
338  NameAndTypeOK: Element '{0}' is either not fixed, or is not fixed with the same value as in the base
339  NameAndTypeOK: The disallowed substitutions, for element '{0}', are not a superset of those of the base element
340  NameAndTypeOK: Element '{0}' has a type that does not derive from that of the base
341  NameAndTypeOK: Derived element '{0}' has fewer Identity Constraints than base element '{1}'
342  NameAndTypeOK: Derived element '{0}' has an Identity Constraint that does not appear on base element '{1}'
343  RecurseAsIfGroup: Element '{0}' belongs to a group of a variety different from that of the base
344  Occurrence range of group is not a valid restriction of occurrence range of base group
345  Recurse: There is not a complete functional mapping between the particles
346  Forbidden restriction of 'any': Choice,Seq,All,Elt
347  Forbidden restriction of 'all': Choice,Seq,Elt
348  Forbidden restriction of 'choice': All,Seq,Leaf
349  Forbidden restriction of 'sequence': Elt
350  Wildcard's occurrence range not a restriction of base wildcard's range
351  Wildcard is not a subset of corresponding wildcard in base
352  Group's occurrence range not a restriction of base wildcard's range
353  RecurseUnordered: There is not a complete functional mapping between the particles
354  MapAndSum: There is not a complete functional mapping between the particles
355  Particle derivation: Invalid content spec node type
356  NodeIDMap overflows and exceeds the largest available size


