#!c:/cygwin64/bin/bash

set -e
set -x

PATH="/cygdrive/c/cygwin64/bin:$PATH"

if [ "$compiler" = "vc15" ]; then
  if [ ! -f /cygdrive/c/tools/vcpkg/installed/x64-windows/bin/icuuc65.dll ]; then
    cd "$(cygpath -u "c:\\tools\\vcpkg")"
    git pull
    ./bootstrap-vcpkg.bat
    ./vcpkg install icu:x64-windows curl:x64-windows
  fi
fi
