$quote "
$set 1
  2  Notation '{0}' has already been declared
  3  Attribute '{0}' has already been declared declared for element '{1}'
  4  Encoding ({0}, from XMLDecl or manually set) contradicts the auto-sensed encoding, ignoring it
  5  Element '{0}' was referenced in a content model but never declared
  6  Element '{0}' was referenced in an attlist but never declared
  9  Expected comment or CDATA
 10  Expected an attribute name
 11  Expected a notation name
 12  Repetition of individual elements is not legal for mixed content models
 13  Bad default attribute declaration
 14  Expected default attribute declaration, assuming #IMPLIED 
 15  Attribute list syntax error
 16  Expected equal sign
 17  Duplication attribute name
 18  Bad ID, '{0}', for xml:lang attribute
 19  Expected an element name
 20  Must start with an XMLDecl
 21  Comments must start with <!--
 22  Invalid document structure
 23  Expected a 'version=', 'encoding=', or 'standalone='
 24  Bad XML version string
 25  Unsupported XML version, '{0}'
 26  Unterminated XML decl
 27  Bad XML encoding declaration, '{0}'
 28  Bad standalone declaration
 29  Unterminated comment
 30  Processing instruction name expected
 31  Unterminated processing instruction
 32  Invalid character (Unicode: 0x{0})
 33  Unexpected text before root element
 34  Unterminated start tag, '{0}'
 35  Expected an attribute value
 36  Unterminated end tag
 37  Expected type (CDATA, ID, NMTOKEN, ..), for attribute '{0}' of element '{1}'
 38  Expected end of tag '{0}'
 39  Expected tag name, comment, PI, or other markup
 40  Not valid after content
 41  Expected comment
 42  Expected comment or processing instruction
 43  Expected whitespace
 44  No root element in DOCTYPE
 45  Expected quoted string
 46  Expected public id
 47  Invalid character in public id (Unicode: 0x{0})
 48  Unterminated DOCTYPE declaration
 49  Invalid character in internal subset (Unicode: 0x{0})
 50  Expected CDATA section
 51  Invalid initial name character
 52  Invalid name character
 53  Unexpected whitespace
 54  Invalid character in attribute value (Unicode: 0x{0})
 55  Expected a markup declaration
 56  Text declaration not legal here
 57  Conditional section in internal subset
 58  Expected parameter entity name
 59  Unterminated entity declaration, '{0}'
 60  Invalid character reference
 61  Unterminated character reference
 62  Expected entity name for reference
 63  Entity '{0}' was not found
 64  Unparsed entitty references, '{0}', not valid here
 65  Unterminated entity reference
 66  Recursive entity expansion
 67  Partial markup in entity value
 68  Unterminated element declaration, '{0}'
 69  Expected content specification expression for element '{0}'
 70  Expected asterisk
 71  Unterminated Content model
 72  Expected system id
 73  Expected system or public id
 74  Unterminated notation declaration
 75  Expected ',', '|', or ')' characters
 76  Expected '|' or ')' characters
 77  Expected ',' or ')' characters or close parenthesis in content model of element '{0}'
 78  Expected enumeration value for attribute '{0}'
 79  Expected | enumeration separator, or closing paren
 80  Unterminated entity literal
 81  There are more end tags than start tags
 82  Reference to external declaration in standalone document. Entity={0}
 83  Expected an open parenthesis
 84  The attribute '{0}' is already used in element '{1}'
 85  A '<' character cannot be used in attribute '{0}', except through &lt;
 86  A leading surrogate character was not followed by a legal second character
 87  Expected ']]>' to end a conditional section
 88  Expected INCLUDE or IGNORE here
 89  Expected [ to follow INCLUDE or IGNORE
 90  Expected a TextDecl here: <?xml ....
 91  Expected a XMLDecl here: <?xml ....
 92  Unexpected end of entity {0}
 93  A PE propogated out of the int/ext subset, discarding extra text
 94  An extra ] character was found an ignored
 95  PE refs are not allowed inside markup in the internal subset
 96  An entity propogated out of the content section into Miscellaneous
 97  Expected &# to be followed by a numeric character value
 98  Expected an open bracket ('[') here
 99  The sequence ']]>' is not allowed in character data
100  Illegal sequence '--' in comment
101  Unterminated CDATA section
102  Expected NDATA
103  NDATA is not legal for parameter entities
104  Hex radix character refs must use 'x', not 'X'
105  '{0}' has already been set. Ignoring redundant setting
106  The XMLDecl strings must be in the order: version, encoding, standalone
107  External entities cannot be referred to from attribute values
108  The XML or Text decl must start with '<?xml ', not '<?XML '
109  Expected a literal entity value or PUBLIC/SYSTEM id
110  '{0}' is not a valid digit for the indicated radix
111  The input ended before all started tags were ended. Last tag started was '{0}'
112  The content model for element '{0}' is ambiguous
113  Nested CDATA sections are not allowed
114  The prefix '{0}' has not been mapped to any URI
115  The start and the end tag were in the different entities
116  The main XML document cannot be empty
117  CDATA is not allowed outside the root element
118  Only numeric character entities or special character entities are legal here
119  Got an unexpected trailing surrogate character
120  No processing instruction starts with 'xml'
121  The XML or Text declaration must start at line/column 1/1
122  The 'version=' string is required in an XMLDecl
123  The 'standalone=' string is only allowed in the main XML entity
124  When namespaces are enabled, a name can have only one colon character
125  When namespaces are enabled, the colon cannot be the first or last character
126  Colons are not allowed in this name when namespaces are enabled
127  A system exception occured during processing
128  An exception occured! Type:{0}, Message:{1}
129  Unexpected end of file exception. Message: {0}


$set 2
  2  Unknown element '{0}'
  3  Attribute '{0}' not defined
  4  Notation '{0}' was referenced but never declared
  5  Root element different from DOCTYPE
  6  Required attribute '{0}' was not provided
  7  Element '{0}' is not valid for content model: '{1}'
  8  ID attributes must be #IMPLIED or #REQUIRED
  9  This type of attribute cannot have an empty value
 10  Element '{0}' has already been declared
 11  Element '{0}' has more than one ID attribute
 12  ID '{0}' has already been used
 13  ID attribute '{0}' was referenced but never declared
 14  Attribute '{0}' refers to an unknown notation '{1}'
 15  Element '{0}' was used in the DOCTYPE but never declared
 16  Empty content not valid for content model: '{0}'
 17  Attribute '{0}' is not declared for element '{1}'
 18  Attributes of type ENTITY/ENTITIES must refer to an external, unparsed entity
 19  Attribute '{0}' refers to an unknown entity '{1}'
 20  Not enough elements to match content model : '{0}'
 21  No character data is allowed by content model
 22  Attribute '{0}' does not match its defined enumeration or notation list
 23  The values for attribute '{0}' must be names or name tokens
 24  Attribute '{0}' does not support multiple values
 25  Attribute '{0}' has a value, '{1}', that does not match its #FIXED value, '{2}'
 26  Element types cannot be duplicated in Mixed content models


$set 3
  2  The index is beyond the array bounds 
  3  The new size is less than the old one
  4  The index given was beyond the max attribute index
  5  The passed AttTypes value is not known
  6  The passed DefAttTypes value is not known
  7  The bit index was beyond the set size
  8  The buffer manager cannot provide any more buffers
  9  The passed buffer was not found in this manager's pool
 10  The pointer has not been set
 11  The binary operation node had a unary node type
 12  The content type must be mixed or children
 13  PCDATA nodes are not valid here
 14  The {0} operation is invalid for the spec type
 15  The unary operation node had a binary node type
 16  Unknown content model type
 17  Unknown content spec type
 18  The parent element has no content spec node
 19  The creation reason enum has an unknown value
 20  The element stack is empty
 21  The element stack index given was beyond the stack top
 22  The element stack was already empty when a pop request occured
 23  A parent operation was requested, but only one element is on the stack
 24  The enumerator contains no more elements
 25  Could not open file: {0}
 26  Could not query the current file position
 27  Could not close the file
 28  Could not seek to end of file
 29  Could not seek to required position in file
 30  Could not duplicate the handle
 31  Could not read data from file
 32  Could not reset file to beginning
 33  Could not acertain the file size
 34  Could not determine base pathname of the file
 35  The base path had too few levels to weave in relative part
 36  Parse may not be called while parsing
 37  A DOCTYPE was seen but the installed validator does not understand DTDs
 38  Could not open DTD file '{0}'
 39  Could not open external entity '{0}'
 40  The end of input was not expected
 41  The hash modulus cannot be zero
 42  Hashing the key returned an invalid bad hash value
 43  The key '{0}' could not be found in the hash table
 44  Could not create mutex
 45  Could not close mutex
 46  Could not lock mutex
 47  Could not unlock mutex
 48  Could not destroy mutex
 49  Error on {0} NetAccessor. Msg: {1}
 50  The NetAccessor could not be initialized. Error={0}
 51  The host/address '(0}' could not be resolved
 52  Could not create the socket for URL '{0}'. Error={1}
 53  Could not connect to the socket for URL '{0}'. Error={1}
 54  Could not write to the socket. Error={0}
 55  Could not read from the socket. Error={0}
 56  The element {0} already exists
 57  Hashing the key returned an invalid bad hash value
 58  The passed id is not valid for this pool
 59  The modulus value cannot be zero
 60  The indicated reader id was never found
 61  The auto encoding enum has an unknown value
 62  Could not decode first line of entity: {0}
 63  End of input was hit in the middle of a multibyte sequence
 64  The current transcoding service does not support source offset information
 65  EBCDIC files must provide an encoding= string
 66  The primary document entity could not be opened. Id={0}
 67  Unbalanced start/end tags found, cannot continue
 68  The call to scanNext() is illegal at this time
 69  The index is past the top of stack
 70  The stack is empty, cannot access members
 71  The target buffer cannot have a max size of zero
 72  The given radix is not supported. Use 2, 8, 10, or 16
 73  The target buffer is too small to accept the results
 74  The start index is past the end of the string
 75  The represented value overflowed the output binary result
 76  Could not write to standard err
 77  Could not write to standard out
 78  Could not write to console
 79  String pool id was not legal
 80  Could not create a default transcoder
 81  The maximum size to xlat is larger than the declared block size
 82  Unicode char 0x{0} is not representable in encoding {1}
 83  Character {0} is not valid for encoding {1}
 84  The requested block size is not equal to the size set during construction
 85  An invalid multi-byte source text sequence was encountered
 86  {0} is not a valid value for encoding {1}
 87  Leading surrogate was not followed by trailing
 88  Could not create a converter for encoding: {0}
 89  The URL was not correctly formed
 90  The URL used an unsupported protocol
 91  Unsupported URL protocol: '{0}'
 92  Only localhost is supported at this time
 93  No protocol prefix present
 94  Expected // after protocol
 95  % must be followed by two hex digits
 96  Unterminated host component
 97  The base part of the URL cannot be relative
 98  The base part has too few levels to weave in relative part
 99  The port field must be a 16 bit decimal number
100  The passed index is past the end of the vector
101  The element id was invalid
102  When reusing the validator, no internal subset is allowed
103  The passed recognizer encoding was not known


